name: flutter_daw_mock_ui
description: Mock Audio Widgets Demo

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.0.1
  cupertino_icons: ^1.0.2
  graphx: ^1.0.3
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  collection: ^1.17.0
  file_picker: ^5.2.5
  flutter_rust_bridge: ^1.6.0
  json_serializable: ^6.0.1
  json_annotation: ^4.8.0
  desktop_drop: ^0.4.0
  augmented_midi_editor:
    path: ../../../dart/augmented_midi_editor

dev_dependencies:
  flutter_test:
    sdk: flutter

  ffigen: ^7.2.4
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.0
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.14.0

flutter:
  uses-material-design: true
