[package]
name = "audio-processor-graph"
version = "0.1.0"
edition = "2018"

[dependencies]
audio-processor-traits = { version = "^0.3", path = "../audio-processor-traits" }
daggy = "^0.7.0"
thiserror = "^1.0.26"
audio-garbage-collector = { path = "../audio-garbage-collector" }
concread = "0.2.19"

[dev-dependencies]
audio-processor-utility = { path = "../audio-processor-utility" }
audio-processor-time = { path = "../audio-processor-time" }
augmented-dsp-filters = { path = "../../dsp/dsp-filters" }
audio-processor-standalone = { path = "../../application/audio-processor-standalone" }