[package]
name = "audio-processor-graph"
version = "0.1.0"
edition = "2018"

[dependencies]
audio-processor-traits = { version = "1.0.0-alpha.4", path = "../audio-processor-traits" }
daggy = "^0.7.0"
thiserror = "^1.0.26"
audio-garbage-collector = { path = "../audio-garbage-collector" , version = "1.0.0-alpha.3" }
num-traits = "0.2.14"
augmented_oscillator = { path = "../oscillator" , version = "1.0.0-alpha.4" }

[dev-dependencies]
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers" , version = "1.0.0-alpha.4" }
audio-processor-utility = { path = "../audio-processor-utility" }
audio-processor-time = { path = "../audio-processor-time" , version = "0.1.0-alpha.2" }
augmented-dsp-filters = { path = "../../dsp/dsp-filters" , version = "1.0.0-alpha.4" }
audio-processor-standalone = { path = "../../application/audio-processor-standalone" , version = "1.0.0-alpha.8" }
assert_no_alloc = { version = "1.1.2", features = ["warn_release"], default-features = false }

criterion = "^0.3.4"

[package.metadata.augmented]

[[bench]]
name = "graph_processor_bench"
harness = false
