[package]
name = "looper-udl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
wisual-logger = "0.1"
looper-processor = { path = "../looper-processor" }
uniffi = "0.17"
uniffi_macros = "0.17"

[build-dependencies]
uniffi_build = "0.17"
uniffi_bindgen = "0.17"
cbindgen = "0.20.0"
