[package]
name = "audio-processor-utility"
version = "0.1.0"
edition = "2018"

[package.metadata.augmented]
processor_examples = ["gain", "mono", "pan"]
private = false

[dependencies]
audio-processor-traits = { version = "^0.3", path = "../audio-processor-traits" }
audio-garbage-collector = { path = "../audio-garbage-collector" }

[dev-dependencies]
audio-processor-standalone = { version = "0.1.5", path = "../../application/audio-processor-standalone" }
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers" }