[package]
name = "audio-processor-utility"
version = "2.5.0"
description = "Utility AudioProcessor implementations (pan, gain, mono, noise)"
edition = "2018"
license = "MIT"
authors = ["Pedro Tacla Yamada (@yamadapc) <tacla.yamada@gmail.com>"]
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[package.metadata.augmented]
processor_examples = ["gain", "mono", "pan"]
private = false

[dependencies]
audio-processor-traits = { version = "4.3.0", path = "../audio-processor-traits" }
audio-garbage-collector = { path = "../audio-garbage-collector" , version = "1.2.0" }
assert_no_alloc = "1.1"
rand = { version = "0.8", features = ["small_rng"] }

[dev-dependencies]
audio-processor-standalone = { version = "3.5.0", path = "../../application/audio-processor-standalone" }
audio-processor-testing-helpers = { version = "2.7.0", path = "../../testing/audio-processor-testing-helpers" }
