name: Download target
description: Download rust target dir

runs:
  using: composite
  steps:
      - name: Download build target
        uses: actions/download-artifact@v4
        with:
          name: build_target_${{ matrix.os }}.tar.gz
          path: target.tar.gz
    
      - name: Untar build outputs
        run: tar -xvzf target.tar.gz