accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MIT-0",
    "Zlib",
    "MPL-2.0",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "OFL-1.1",
    "NOASSERTION",
    "BSD-1-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "zlib-acknowledgement",
    "OpenSSL",
    "LGPL-3.0",
    "0BSD",
    "Unicode-DFS-2016",
]
ignore-dev-dependencies = true

# Dart is multi-licensed as MIT as well
[dart-sys]
accepted = ["GPL-3.0"]

# These are internal crates
[daw_ui]
accepted = ["GPL-3.0"]

[metronome]
accepted = ["AGPL-3.0"]

[rust_lib_metronome]
accepted = ["AGPL-3.0"]
