[workspace]
members = [
  "crates/*",
  "crates/apps/plugin-host/plugin-host-cli",
  "crates/apps/plugin-host/plugin-host-gui2",
  "crates/apps/plugin-host/plugin-host-lib",
  "crates/scripts/autosync-submodules",
  "crates/spikes/example-iced-audio-viz",
  "crates/spikes/example-iced-xcode-integration",
]
exclude = [
  "crates/apps",
  "crates/basedrop",
  "crates/baseview",
  "crates/cpal",
  "crates/darwin-webkit",
  "crates/gfx",
  "crates/iced",
  "crates/iced_audio",
  "crates/libloading",
  "crates/lyon",
  "crates/pathfinder",
  "crates/piet",
  "crates/plotters",
  "crates/scripts",
  "crates/spikes",
  "crates/vst",
]

[profile.bench]
debug = true

[patch.crates-io]
pathfinder_canvas = { path = "./crates/pathfinder/canvas" }
basedrop = { path = "./crates/basedrop" }
gfx-hal = { path = "./crates/gfx/src/hal" }
gfx-backend-metal = { version = "*", path = "./crates/gfx/src/backend/metal", features = ["cross"] }
iced = { version = "^0.3.0", path = "./crates/iced" }
lyon_tessellation = { path = "./crates/lyon/crates/tessellation", features = ["profiling"] }
wisual-logger = { path = "./crates/wisual-logger" }
libloading = { path = "./crates/libloading" }
vst = { path = "./crates/vst" }
