[workspace]
members = [
  "crates/*",
  "crates/scripts/autosync-submodules",
]
exclude = [
  "crates/basedrop",
  "crates/cpal",
  "crates/darwin-webkit",
  "crates/example-druid-audio-viz",
  "crates/iced",
  "crates/baseview",
  "crates/plotters",
  "crates/gfx",
  "crates/iced_audio",
  "crates/scripts",
  "crates/lyon",
  "crates/vst",
  "crates/libloading"
]

[profile.bench]
debug = true

[patch.crates-io]
basedrop = { path = "./crates/basedrop" }
gfx-hal = { path = "./crates/gfx/src/hal" }
gfx-backend-metal = { version = "*", path = "./crates/gfx/src/backend/metal", features = ["cross"] }
iced = { version = "^0.3.0", path = "./crates/iced" }
lyon_tessellation = { path = "./crates/lyon/crates/tessellation", features = ["profiling"] }
wisual-logger = { path = "./crates/wisual-logger" }
libloading = { path = "./crates/libloading" }
vst = { path = "./crates/vst" }
