[workspace]
members = [
  "crates/*",
  "crates/scripts/autosync-submodules",
  "crates/plugin-host-gui/src-tauri",
]
exclude = [
  "crates/plugin-host-gui",
  "crates/basedrop",
  "crates/cpal",
  "crates/darwin-webkit",
  "crates/tauri",
  "crates/example-druid-audio-viz",
  "crates/iced",
  "crates/iced_audio",
  "crates/scripts"
]

[profile.bench]
debug = true
