[workspace]
members = [
  "crates/*",
  "crates/apps/plugin-host/plugin-host-cli",
  "crates/apps/plugin-host/plugin-host-gui2",
  "crates/apps/plugin-host/plugin-host-lib",
  "crates/scripts/autosync-submodules",
  "crates/spikes/example-iced-audio-viz",
  "crates/spikes/example-iced-xcode-integration",
]
exclude = [
  "crates/apps",
  "crates/darwin-webkit",
  "crates/libloading",
  "crates/scripts",
  "crates/spikes",
  "crates/vendor",
]

[profile.bench]
debug = true

[patch.crates-io]
wisual-logger = { path = "./crates/wisual-logger" }

# Vendor overrides
basedrop = { path = "./crates/vendor/basedrop" }
gfx-backend-metal = { version = "*", path = "./crates/vendor/gfx/src/backend/metal", features = ["cross"] }
gfx-hal = { path = "./crates/vendor/gfx/src/hal" }
iced = { version = "^0.3.0", path = "./crates/vendor/iced" }
libloading = { path = "./crates/vendor/libloading" }
lyon_tessellation = { path = "./crates/vendor/lyon/crates/tessellation", features = ["profiling"] }
pathfinder_canvas = { path = "./crates/vendor/pathfinder/canvas" }
vst = { path = "./crates/vendor/vst" }