[workspace]
members = [
  "crates/*",
  "crates/scripts/autosync-submodules",
  "crates/plugin-host-gui/src-tauri",
]
exclude = [
  "crates/plugin-host-gui",
  "crates/basedrop",
  "crates/cpal",
  "crates/darwin-webkit",
  "crates/tauri",
  "crates/example-druid-audio-viz",
  "crates/iced",
  "crates/gfx",
  "crates/iced_audio",
  "crates/scripts"
]

[profile.bench]
debug = true

[patch.crates-io]
gfx-hal = { path = "./crates/gfx/src/hal" }
gfx-backend-metal = { version = "*", path = "./crates/gfx/src/backend/metal", features = ["cross"] }
iced = { version = "^0.3.0", path = "./crates/iced" }
wisual-logger = { path = "./crates/wisual-logger" }
