[workspace]
members = [
  "crates/*",
  "crates/scripts/autosync-submodules",
  "crates/plugin-host-gui/src-tauri"
]
exclude = [
  "crates/plugin-host-gui",
  "crates/basedrop",
  "crates/darwin-webkit",
  "crates/tauri",
  "crates/example-druid-audio-viz",
  "crates/example-iced-audio-viz",
  "crates/audio-processor-iced-design-system",
  "crates/iced",
  "crates/scripts"
]

[profile.bench]
debug = true
