[workspace]
members = [
  "crates/*",
  "crates/plugin-host-gui/src-tauri"
]
exclude = [
  "crates/plugin-host-gui",
  "crates/basedrop",
  "crates/darwin-webkit",
  "crates/tauri"
]

[profile.bench]
debug = true
