[package]
name = "rust_lib_metronome"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"
license = "AGPL-3.0"

[lib]
crate-type = ["staticlib", "lib", "cdylib"]

[dependencies]
anyhow = "1.0.52"
log = "^0.4.14"
flutter_rust_bridge = "=2.3.0"
lazy_static = "1.4.0"
urlencoding = "2.1.2"
ringbuf = "0.2.8"

wisual-logger = { path = "../../../augmented/ops/wisual-logger", version = "0.1.4" }
audio-processor-metronome = { path = "../../../augmented/audio/audio-processor-metronome", version = "3.5.0" }
audio-processor-standalone = { path = "../../../augmented/application/audio-processor-standalone", version = "3.5.0", default-features = false }
audio-garbage-collector = { path = "../../../augmented/audio/audio-garbage-collector", version = "1.2.0" }
audio-processor-file = { path = "../../../augmented/audio/audio-processor-file", version = "3.3.0" }
audio-processor-traits = { path = "../../../augmented/audio/audio-processor-traits", version = "4.3.0" }
macos-bundle-resources = { path = "../../../augmented/gui/macos-bundle-resources" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
wasm_thread = { version = "0.2.0", features = ["es_modules"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.1"
jni = "0.21.1"
ndk-context = "0.1.1"

[build-dependencies]
cbindgen = "0.24.3"
flutter_rust_bridge_codegen = "2.3.0"

[package.metadata.augmented]
private = true
