[package]
name = "adsr-envelope"
version = "0.1.0"
edition = "2018"
description = "ADSR envelope implementation"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
plotters = { version = "0.3" }
