[package]
name = "tas_v2"
version = "0.0.1"
authors = ["Pedro Tacla Yamada <tacla.yamada@gmail.com>"]

[dependencies]
vst = { git = "https://github.com/rustaudio/vst-rs" }
oscillator = { path = "../oscillator" }

[lib]
name = "tas_v2"
crate-type = ["cdylib"]
