[package]
name = "augmented-audio-gui-basics"
version = "0.1.0"
edition = "2021"

[dependencies]
wisual-logger = { version = "0.1.4", path = "../../ops/wisual-logger" }
winit = "0.27.3"
foreign-types-shared = "0.1"
taffy = "0.2.2"
log = "0.4.17"

[target.'cfg(any(target_os = "linux"))'.dependencies]
skia-safe = { version = "0.54.0" }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
skia-safe = { version = "0.54.0", features = ["metal"] }
objc = "*"
metal = "0.24.0"
cocoa = "0.24.0"
core-graphics-types = "0.1.1"
core-foundation-sys = "0.8.3"
