[package]
name = "audio-processor-bitcrusher"
version = "0.1.0-alpha.1"
edition = "2021"

[[example]]
name = "bitcrusher_vst"
crate-type = ["cdylib"]

[dependencies]
audio-processor-traits = { version = "1.0.0-alpha.3", path = "../audio-processor-traits" }
audio-garbage-collector = { version = "1.0.0-alpha.2", path = "../audio-garbage-collector" }

[dev-dependencies]
audio-processor-standalone = { version = "1.0.0-alpha.7", path = "../../application/audio-processor-standalone", features = ["gui"] }
audio-processor-testing-helpers = { version = "1.0.0-alpha.3", path = "../../testing/audio-processor-testing-helpers" }

[package.metadata.augmented]
processor_examples = ["bitcrusher"]
vst_examples = ["bitcrusher"]
private = true
