[package]
name = "audio-processor-standalone-osc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wisual-logger = "0.1"
log = "^0.4.14"
rosc = "0.6.0"
zeroconf = "0.10.2"
hostname = "0.3.1"