[package]
name = "augmented-audio-wave"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT"

[package.metadata.augmented]
private = true

[dependencies]
audio-processor-traits = { version = "4.3.0", path = "../../audio/audio-processor-traits" }
log = "0.4.17"
audio-processor-analysis = { version = "2.3.0", path = "../../audio/audio-processor-analysis" }
audio-garbage-collector = { version = "1.2.0", path = "../../audio/audio-garbage-collector" }

[target.'cfg(target_os = "linux")'.dependencies]
skia-safe = { version = "0.54.0" }

[target.'cfg(any(target_os="ios", target_os="macos"))'.dependencies]
skia-safe = { version = "0.54.0", features = ["metal"] }

[dev-dependencies]
audio-processor-testing-helpers = { version = "2.7.0", path = "../../testing/audio-processor-testing-helpers" }
audio-processor-file = { version = "3.3.0", path = "../../audio/audio-processor-file" }
wisual-logger = { version = "0.1.4", path = "../../ops/wisual-logger" }
foreign-types-shared = "0.1"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dev-dependencies]
cocoa = "0.24.0"
core-graphics-types = "0.1.1"
objc = "*"
metal = "0.24.0"
winit = "0.27.3"
