[package]
name = "audio-processor-iced-design-system"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { path = "../iced", version = "^0.3.0", features = ["canvas", "tokio"] }
iced_style = { path = "../iced/style" }

[dev-dependencies]
log = "^0.4.14"
wisual-logger = { version = "^0.1", path = "../wisual-logger" }