[package]
name = "audio-processor-metronome"
version = "3.0.0"
description = "Implements a simple metronome processor"
license = "MIT"
edition = "2021"

[dependencies]
augmented_oscillator = { path = "../oscillator" , version = "1.3.0" }
audio-processor-traits = { path = "../audio-processor-traits" , version = "4.1.0" }
audio-processor-standalone = { path = "../../application/audio-processor-standalone" , version = "3.1.0", default-features = false }
audio-garbage-collector = { path = "../audio-garbage-collector" , version = "1.2.0" }
augmented-playhead = { path = "../../data/augmented-playhead" , version = "0.7.0" }
augmented-adsr-envelope = { path = "../adsr-envelope" , version = "0.5.0" }
audio-processor-file = { path = "../audio-processor-file", version = "3.1.0" }
enum_dispatch = "0.3.8"

[dev-dependencies]
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers", version = "2.5.0" }

[package.metadata.augmented]
private = false
processor_examples = ["audio_processor_metronome_example"]
