[package]
name = "audio-processor-sampler"
version = "0.1.0"
edition = "2021"

[dependencies]
audio-processor-traits = { version = "1.0.0-alpha.3", path = "../audio-processor-traits" }
audio-processor-file = { version = "1.0.0-alpha.3", path = "../audio-processor-file" }
audio-garbage-collector = { version = "1.0.0-alpha.2", path = "../audio-garbage-collector" }

[dev-dependencies]
audio-processor-standalone = { version = "1.0.0-alpha.7", path = "../../application/audio-processor-standalone" }
