[package]
name = "audio-processor-traits-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
audio-processor-traits = { version = "1.0.0-alpha.3", path = "../audio-processor-traits" }
syn = "1.0.86"
quote = "1.0.15"
proc-macro2 = "1.0.36"