[package]
name = "augmented-audio-knob"
version = "0.1.0"
edition = "2021"

[dependencies]
skia-safe = { version = "0.54.0", features = ["metal"] }
augmented-audio-gui-basics = { path = "../augmented-audio-gui-basics" }

[dev-dependencies]