[package]
name = "audio-processor-utility"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-processor-traits = { version = "^0.2", path = "../audio-processor-traits" }