[package]
name = "augmented-analytics"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = "0.11.4"
log = "0.4.14"
tokio = { version = "1.10.0", features = ["rt-multi-thread", "rt", "macros"] }
serde = { version = "^1.0.126", features = ["derive"] }
serde_json = "^1.0.64"
serde_urlencoded = "0.7.0"
itertools = "0.10.1"
async-trait = "0.1.51"

[dev-dependencies]
wisual-logger = "0.1.3"
