[package]
name = "audio-processor-dynamics"
version = "2.0.0"
description = "Implements a compressor"
edition = "2021"
license = "MIT"
authors = ["Pedro Tacla Yamada (@yamadapc) <tacla.yamada@gmail.com>"]
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[features]
default = ["f32"]
f32 = ["augmented-audio-volume/f32"]
f64 = ["augmented-audio-volume/f64"]

[dependencies]
audio-processor-traits = { version = "4.1.0", path = "../audio-processor-traits" }
audio-garbage-collector = { version = "1.2.0", path = "../audio-garbage-collector" }
augmented-audio-volume = { path = "../../data/audio-volume" , version = "0.6.0" }

[dev-dependencies]
audio-processor-file = { version = "3.0.0", path = "../audio-processor-file" }
audio-processor-testing-helpers = { version = "2.4.0", path = "../../testing/audio-processor-testing-helpers" }
audio-processor-standalone = { version = "3.0.0", path = "../../application/audio-processor-standalone" }

[package.metadata.augmented]
# uncommenting this will enable snapshot tests
# processor_examples = ["compressor"]
private = false
