[package]
name = "audio-processor-dynamics"
version = "0.1.0"
edition = "2021"

[dependencies]
audio-processor-traits = { version = "1.0.0-alpha.3", path = "../audio-processor-traits" }
audio-garbage-collector = { version = "1.0.0-alpha.2", path = "../audio-garbage-collector" }
augmented-audio-volume = { path = "../../data/audio-volume", default-features = false, features = [] }

[dev-dependencies]
audio-processor-file = { version = "1.0.0-alpha.3", path = "../audio-processor-file" }
audio-processor-testing-helpers = { version = "1.0.0-alpha.3", path = "../../testing/audio-processor-testing-helpers" }