[package]
name = "augmented_oscillator"
version = "0.1.0"
authors = ["Pedro Tacla Yamada <tacla.yamada@gmail.com>"]
edition = "2018"
description = "Very simple implementation of an oscillator."

[dependencies]

[dev-dependencies]
criterion = "^0.3"
ringbuf = "^0.2.6"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
plotters = { version = "0.3" }

[[bench]]
name = "sine_oscillator_benchmark"
harness = false

[package.metadata.augmented]
private = false
