[package]
name = "audio-processor-standalone-midi"
version = "1.11.0"
edition = "2018"
description = "Stand-alone MIDI hosting for a VST host or an `audio-processor-traits` implementor"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[features]
default = ["vst"]
actix = ["dep:actix"]
vst = ["dep:vst"]

[dependencies]
basedrop = "^0.1.2"
thiserror = "^1.0.26"
midir = "0.8"
log = "^0.4.14"
vst = { version = "0.3", path = "../../../vendor/vst", optional = true }

# augmented
atomic-queue = { version = "2.2.0", path = "../../data/atomic-queue" }
audio-processor-traits = { version = "4.2.0", path = "../../audio/audio-processor-traits", features = ["vst"] }
audio-garbage-collector = { path = "../../audio/audio-garbage-collector" , version = "1.2.0" }

actix = { version = "0.13.0", optional = true }

[dev-dependencies]
assert_no_alloc = { version = "1.1.2", features = ["disable_release"], default-features = false }

[package.metadata.augmented]
private = false
