name: metronome
description: A simple metronome app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 < 4.0.0"

dependencies:
  community_charts_flutter: ^1.0.4
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  ffi: ^2.0.1
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  floor: ^1.4.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_mobx: ^2.0.6+5
  flutter_platform_widgets: ^7.0.1
  flutter_rust_bridge: 2.3.0
  flutter_timezone: ^2.1.0
  graphx: ^1.0.12
  intl: ^0.19.0
  logger: ^2.4.0
  macos_ui:
    path: vendor/macos_ui
  mobx: ^2.1.4
  mockito: ^5.3.2
  path_provider: ^2.0.14
  rust_lib_metronome:
    path: rust_builder
  shared_preferences: ^2.0.15
  sqflite: ^2.2.6
  timezone: ^0.9.1
  uuid: ^4.4.2
  wakelock_plus: ^1.2.8

dev_dependencies:
  build_runner: ^2.2.1
  ffigen: ^13.0.0
  floor_generator: ^1.4.1
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^2.0.0
  mobx_codegen: ^2.1.1

flutter_icons:
  ios: "AppIcon"
  image_path: "design/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
