name: metronome
description: A simple metronome app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  charts_flutter: ^0.12.0
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  ffi: ^2.0.1
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  floor: ^1.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^11.0.0
  flutter_mobx: ^2.0.6+4
  flutter_native_timezone: ^2.0.0
  flutter_rust_bridge: ^1.62.0
  graphx: ^1.0.4
  intl: ^0.17.0
  logger: ^1.1.0
  macos_ui:
    path: vendor/macos_ui
  mobx: ^2.1.0
  mockito: ^5.3.2
  shared_preferences: ^2.0.15
  sqflite: ^2.1.0
  timezone: ^0.9.0
  wakelock: ^0.6.2

dev_dependencies:
  build_runner: ^2.2.1
  ffigen: ^6.1.2
  floor_generator: ^1.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^2.0.0
  mobx_codegen: ^2.0.7+3

flutter_icons:
  ios: "AppIcon"
  image_path: "design/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
