[package]
name = "audio-processor-pitch-shifter"
version = "0.1.0"
description = "A phase-vocoder pitch-shifter implementation"
edition = "2021"
license = "MIT"
authors = ["Pedro Tacla Yamada (@yamadapc) <tacla.yamada@gmail.com>"]
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[package.metadata.augmented]
private = true

[dependencies]
audio-processor-analysis = { path = "../audio-processor-analysis" , version = "2.3.0" }
audio-processor-traits = { path = "../audio-processor-traits" , version = "4.3.0" }
audio-garbage-collector = { path = "../audio-garbage-collector" , version = "1.2.0" }

[dev-dependencies]
audio-processor-standalone = { version = "3.4.0", path = "../../application/audio-processor-standalone" }
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers" , version = "2.6.0" }
audio-processor-file = { path = "../audio-processor-file", version = "3.2.0" }
assert_no_alloc = { version = "1.1.2", features = ["disable_release"], default-features = false }
