[package]
name = "audio-processor-pitch-shifter"
version = "0.1.0"
edition = "2021"

[package.metadata.augmented]
private = true

[dependencies]
audio-processor-analysis = { path = "../audio-processor-analysis" , version = "0.1.0-alpha.4" }
audio-processor-traits = { path = "../audio-processor-traits" , version = "1.0.0-alpha.4" }
audio-garbage-collector = { path = "../audio-garbage-collector" , version = "1.0.0-alpha.2" }

[dev-dependencies]
audio-processor-standalone = { version = "1.0.0-alpha.8", path = "../../application/audio-processor-standalone" }
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers" , version = "1.0.0-alpha.4" }
audio-processor-file = { path = "../audio-processor-file" , version = "1.0.0-alpha.4" }
assert_no_alloc = { version = "1.1.2", features = ["warn_release"], default-features = false }
