[package]
name = "augmented-audio-metrics"
version = "0.1.0"
edition = "2021"
description = "Placeholder crate; will eventually contain metrics mechanisms for augmented applications."
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
log = "^0.4.14"

[package.metadata.augmented]
private = false