[package]
name = "audio-garbage-collector-v2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-queue = { path = "../../data/atomic-queue" }
circular-data-structures = { path = "../../data/circular-data-structures" }

[dev-dependencies]
log = "^0.4.14"
wisual-logger = "^0.1.2"
rand = "^0.8.4"