[package]
name = "plugin-host-gui"
version = "0.1.0"
description = ""
authors = ["Pedro Tacla Yamada"]
default-run = "plugin-host-gui"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.0" }

[dependencies]
log = "^0.4.14"
wisual-logger = "^0.1.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.1", features = ["api-all"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
