[package]
name = "audio-processor-standalone-gui"
version = "0.3.0"
description = "Provides generic `iced` GUI for implementations of `audio_processor_traits::parameters::AudioProcessorHandle`"
edition = "2021"
license = "MIT"
authors = ["Pedro Tacla Yamada (@yamadapc) <tacla.yamada@gmail.com>"]
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[features]
default = [
    "iced",
    "iced_audio",
    "iced_baseview",
    "augmented-iced-editor",
    "audio-processor-iced-design-system",
    "baseview",
    "wgpu",
    "iced/tokio",
    "iced_baseview/tokio",
]
glow = [
    "iced/glow",
    "iced_baseview/glow",
    "iced/canvas",
    "iced_baseview/glow_canvas",
    "audio-processor-iced-design-system/glow",
]
wgpu = [
    "iced/wgpu",
    "iced_baseview/wgpu",
    "iced/canvas",
    "iced_baseview/wgpu_canvas",
    "audio-processor-iced-design-system/wgpu",
]

[dependencies]
audio-processor-traits = { version = "2.1.0",  path = "../../audio/audio-processor-traits" }
vst = { version = "0.3", path = "../../../vendor/vst" }

# GUI dependencies
iced = { version = "0.4.2", default-features = false, optional = true }
iced_baseview = { git = "https://github.com/yamadapc/iced_baseview", rev = "2714c97a431b1c7eba8bc0c67055ac35e80b29ce", default-features = false, optional = true }
iced_audio = { version = "0.8.0", default-features = false, optional = true }
baseview = { git = "https://github.com/yamadapc/baseview", rev = "a82acc4017443e652fd218d28d20f2546be3bf22", optional = true }
augmented-iced-editor = { path = "../../gui/iced-editor", optional = true }
audio-processor-iced-design-system = { path = "../../gui/audio-processor-iced-design-system", default-features = false, optional = true, version = "0.2.1" }

[package.metadata.augmented]
private = false
