[package]
name = "audio-processor-file"
version = "0.1.0"
edition = "2021"

[dependencies]
# Error / Logging
log = "^0.4.14"
thiserror = "^1.0.30"

# Parallelism
rayon = "^1.5.1"

# Audio read/write respectively
symphonia = { version = "^0.4.0", features = ["mp3", "wav", "flac", "isomp4", "aac"] }
symphonia-bundle-mp3 = "^0.4.0"
hound = "^3.4.0"

# Augmented
audio-garbage-collector = { path = "../../../augmented/audio/audio-garbage-collector" , version = "1.0.0-alpha.2" }
audio-processor-traits = { version = "1.0.0-alpha.1", path = "../../../augmented/audio/audio-processor-traits" }
augmented-metrics = { path = "../../ops/augmented-metrics" }
augmented-convert-sample-rate = { path = "../../../augmented/dsp/convert-sample-rate" , version = "1.0.0-alpha.1" }

[dev-dependencies]
audio-processor-testing-helpers = { path = "../../../augmented/testing/audio-processor-testing-helpers" }

[package.metadata.augmented]
