[package]
name = "audio-garbage-collector"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
thiserror = "^1.0.26"
basedrop = "^0.1.2"
log = "^0.4.14"

[dev-dependencies]
wisual-logger = { version = "^0.1", path = "../../ops/wisual-logger" }

[package.metadata.augmented]
private = false