[package]
name = "audio-garbage-collector"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0.26"
basedrop = "^0.1.2"
log = "^0.4.14"

[dev-dependencies]
wisual-logger = { version = "^0.1.2", path = "../../ops/wisual-logger" }