[package]
name = "audio-processor-testing-helpers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-processor-traits = { version = "0.3", path = "../../audio/audio-processor-traits" }
augmented_oscillator = { path = "../../audio/oscillator" , version = "1.0.0-alpha.2" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
plotters = { version = "0.3" }
