[package]
name = "audio-processor-analysis"
version = "2.2.0"
edition = "2018"
description = "Audio analysis processors"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[features]
visualization = ["piet", "piet-common", "audio-processor-testing-helpers", "audio-processor-file"]

[dependencies]
audio-garbage-collector = { path = "../audio-garbage-collector" , version = "1.2.0" }
audio-processor-traits = { version = "4.2.0", path = "../audio-processor-traits" }
rustfft = "6.0.1"
log = "0.4.14"
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers", version = "2.5.0", optional = true }
audio-processor-file = { path = "../audio-processor-file", version = "3.1.0", optional = true }
numeric_literals = "0.2.0"

piet = { version = "0.5.0", optional = true }
piet-common = { version = "0.5.0", features = ["png"], optional = true }

[dev-dependencies]
wisual-logger = { version = "0.1", path = "../../ops/wisual-logger" }
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers", version = "2.5.0" }
audio-processor-file = { path = "../audio-processor-file", version = "3.1.0" }
# nannou = "0.18"
image = "0.24.3"
clap = "2.34.0"
piet = "0.5.0"
piet-common = { version = "0.5.0", features = ["png"] }

[package.metadata.augmented]
private = false
