[package]
name = "audio-processor-analysis"
description = "Analysis AudioProcessors"
version = "0.1.0"
edition = "2018"

[dependencies]
audio-garbage-collector = { path = "../audio-garbage-collector" , version = "1.0.0-alpha.2" }
audio-processor-traits = { version = "1.0.0-alpha.1", path = "../audio-processor-traits" }
rustfft = "6.0.1"

[dev-dependencies]
log = "0.4.14"
wisual-logger = { version = "0.1", path = "../../ops/wisual-logger" }
audio-processor-testing-helpers = { path = "../../testing/audio-processor-testing-helpers" }
audio-processor-file = { path = "../audio-processor-file" , version = "1.0.0-alpha.1" }
image = "0.23.14"
clap = "2.34.0"

[package.metadata.augmented]
private = true
