[package]
name = "augmented-iced-editor"
version = "0.1.0"
edition = "2018"
description = "Iced based VST editor"
license = "MIT"
authors = ["Pedro Tacla Yamada (@yamadapc) <tacla.yamada@gmail.com>"]
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[features]
default = ["wgpu", "tokio"]
tokio = ["iced_baseview/tokio", "iced/tokio"]
glow = ["iced/glow", "iced/canvas", "iced_baseview/glow", "iced_baseview/glow_canvas"]
wgpu = ["iced/wgpu", "iced/canvas", "iced_baseview/wgpu_canvas", "iced_baseview/wgpu"]

[dependencies]
iced = { version = "0.4.2", default-features = false }
log = "^0.4.14"
vst = { version = "0.3.0", path = "../../../vendor/vst" }
wisual-logger = { version = "0.1.4", path = "../../ops/wisual-logger" }

baseview = { git = "https://github.com/yamadapc/baseview", rev = "a82acc4017443e652fd218d28d20f2546be3bf22" }
iced_baseview = { git = "https://github.com/yamadapc/iced_baseview", rev = "2714c97a431b1c7eba8bc0c67055ac35e80b29ce", default-features = false, optional = true }
raw-window-handle = "0.4.3"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "^0.2.7"
cocoa = "^0.24.0"

[package.metadata]
augmented.private = false
