[package]
name = "dsp-filters"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "^0.4.0"
audio-processor-traits = { version = "^0.3", path = "../audio-processor-traits" }
