[package]
name = "plugin-host-gui2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0.25"
log = "^0.4.14"
iced = { version = "^0.3.0", path = "../iced" }

audio-processor-iced-design-system = { path = "../audio-processor-iced-design-system" }
plugin-host-lib = { path = "../plugin-host-lib" }
wisual-logger = { path = "../wisual-logger" }