[package]
name = "plugin-host-gui2"
version = "0.1.0"
edition = "2018"

[dependencies]
dirs = "^3.0.2"
log = "^0.4.14"
tinyfiledialogs = "^3.0"
thiserror = "^1.0.25"

audio-processor-iced-design-system = { path = "../audio-processor-iced-design-system" }
iced = { version = "^0.3.0", path = "../iced" }
plugin-host-lib = { path = "../plugin-host-lib" }
wisual-logger = { path = "../wisual-logger" }