[package]
name = "augmented-dsp-filters"
version = "0.1.0"
edition = "2018"
description = "Audio filters (port of C++ DSPFilters)"

[dependencies]
num = "^0.4.0"
audio-processor-traits = { version = "^0.3", path = "../../audio/audio-processor-traits" }
