[package]
name = "audio-processor-standalone"
version = "1.0.0-alpha.7"
edition = "2018"
description = "Stand-alone Audio/MIDI CLI runner for `audio-processor-traits`"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"
readme = "README.md"

[features]
default = []
gui = [
    "iced",
    "iced_audio",
    "iced_baseview",
    "iced-editor",
    "audio-processor-iced-design-system",
    "baseview",
    "glow",
    "iced/tokio",
    "iced_baseview/tokio",
]
glow = [
    "iced/glow",
    "iced_baseview/glow",
    "iced/glow_canvas",
    "iced_baseview/glow_canvas",
    "audio-processor-iced-design-system/glow",
]
wgpu = [
    "iced/wgpu",
    "iced_baseview/wgpu",
    "iced/canvas",
    "iced_baseview/canvas",
    "audio-processor-iced-design-system/wgpu",
]

[dependencies]
# Logging & options
clap = "^2.33.3"
log = "^0.4.14"
wisual-logger = { version = "^0.1", path = "../../ops/wisual-logger" }
itertools = "0.10.1"

# Augmented
audio-processor-file = { path = "../../audio/audio-processor-file", version = "1.0.0-alpha.3" }
audio-garbage-collector = { path = "../../audio/audio-garbage-collector", version = "1.0.0-alpha.2" }
audio-processor-traits = { version = "1.0.0-alpha.3", path = "../../audio/audio-processor-traits" }
augmented-midi = { path = "../../data/augmented-midi", version = "1.0.0-alpha.3" }

# Audio
basedrop = "^0.1.2"
cpal = { version = "^0.13.3" }
ringbuf = "^0.2.5"
vst = { version = "0.2.1", path = "../../../vendor/vst" }

# GUI dependencies
iced = { version = "^0.3.0", path = "../../../vendor/iced", default-features = false, optional = true }
iced_baseview = { path = "../../../vendor/iced-baseview", default-features = false, optional = true }
iced_audio = { path = "../../../vendor/iced_audio", default-features = false, optional = true }
audio-processor-iced-design-system = { path = "../../gui/audio-processor-iced-design-system", default-features = false, optional = true }
baseview = { path = "../../../vendor/baseview", optional = true }
iced-editor = { path = "../../gui/iced-editor", optional = true }

[target.'cfg(not(target_os = "ios"))'.dependencies]
audio-processor-standalone-midi = { version = "1.0.0-alpha.4", path = "../audio-processor-standalone-midi" }

[dev-dependencies]
atomic-queue = { version = "1.0.0-alpha.2", path = "../../data/atomic-queue" }
audio-processor-testing-helpers = { version = "1.0.0-alpha.3", path = "../../testing/audio-processor-testing-helpers" }

[package.metadata.augmented]
private = false
