[package]
name = "audio-processor-standalone"
version = "3.2.0"
edition = "2018"
description = "Stand-alone Audio/MIDI CLI runner for `audio-processor-traits`"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"
readme = "README.md"

[features]
default = ["midi", "vst"]
gui = ["audio-processor-standalone-gui"]
clap = []
vst = ["dep:vst", "audio-processor-traits/vst", "audio-processor-standalone-midi/vst"]
midi = ["audio-processor-standalone-midi", "dep:augmented-midi"]

[dependencies]
# Logging & options
clap = "^2.33.3"
log = "^0.4.14"
wisual-logger = { version = "^0.1", path = "../../ops/wisual-logger" }
itertools = "0.10.1"
thiserror = "^1.0.25"

# Augmented
audio-processor-file = { path = "../../audio/audio-processor-file", version = "3.1.0" }
audio-garbage-collector = { path = "../../audio/audio-garbage-collector", version = "1.2.0" }
audio-processor-traits = { version = "4.2.0", path = "../../audio/audio-processor-traits" }
augmented-midi = { path = "../../data/augmented-midi", version = "1.6.0", optional = true }

# Audio
basedrop = "^0.1.2"
cpal = { version = "0.15.2", features = ["oboe-shared-stdcxx"] }
ringbuf = "^0.2.5"
vst = { version = "0.3", path = "../../../vendor/vst", optional = true }

audio-processor-standalone-gui = { path = "../audio-processor-standalone-gui", optional = true , version = "0.9.0" }

[target.'cfg(not(target_os = "ios"))'.dependencies]
audio-processor-standalone-midi = { version = "1.6.0", path = "../audio-processor-standalone-midi", optional = true }

[dev-dependencies]
atomic-queue = { version = "2.0.0", path = "../../data/atomic-queue" }
audio-processor-testing-helpers = { version = "2.5.0", path = "../../testing/audio-processor-testing-helpers" }
mockall = "0.11.1"

[package.metadata.augmented]
private = false
