[package]
name = "example-file-streaming"
version = "0.1.0"
edition = "2021"

[dependencies]
audio-processor-standalone = { version = "1.0.0-alpha.13",path = "../../augmented/application/audio-processor-standalone" }
audio-processor-file = { version = "1.0.0-alpha.9", path = "../../augmented/audio/audio-processor-file" }
audio-processor-traits = { version = "1.0.0-alpha.8", path = "../../augmented/audio/audio-processor-traits" }
ringbuf = "0.2.8"
log = "0.4.17"
wisual-logger = "0.1.4"
audio-processor-testing-helpers = { version = "1.0.0-alpha.8", path = "../../augmented/testing/audio-processor-testing-helpers" }
symphonia = "0.5.1"