name: macOS

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    name: Build macos dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-macos"
      - name: Install cargo-nextest
        run: |
          if ! [ -x "$(command -v cargo-nextest)" ]; then
            echo "::group::Installing cargo-nextest"
            cargo install cargo-nextest
            echo "::endgroup::"
          fi
          which cargo-nextest
      - name: Install uniffi bindgen
        run: |
          if ! [ -x "$(command -v uniffi-bindgen)" ]; then
            echo "::group::Installing uniffi_bindgen"
            cargo install --version 0.15.2 uniffi_bindgen
            echo "::endgroup::"
          fi
          which uniffi_bindgen