name: CI builds

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rust:
    strategy:
      matrix:
        os: [macos-14, ubuntu-20.04]
      fail-fast: false
    uses: ./.github/workflows/rust.yml
    with:
      os: matrix.os

  dart:
    uses: ./.github/workflows/dart.yml

  web:
    uses: ./.github/workflows/web.yml
