name: Default

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    name: Run unit-tests on rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: ./scripts/install-ubuntu-dependencies.sh
        if: matrix.os == 'ubuntu-latest'
      - name: Run tests
        run: cargo test --verbose --workspace --exclude plugin-host-gui
        if: matrix.os == 'macos-latest'
      - name: Non-OSX test
        run: |
          cargo test --no-default-features --verbose --workspace \
              --features story \
              --exclude plugin-host-gui \
              --exclude darwin-webkit \
              --exclude webview-holder \
              --exclude macos-bundle-resources
  lint-rust:
    name: Lint rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: ./scripts/install-ubuntu-dependencies.sh
        if: matrix.os == 'ubuntu-latest'
      - name: Run clippy
        run: cargo clippy --verbose --workspace --exclude plugin-host-gui
        if: matrix.os == 'macos-latest'
      - name: Run check
        run: cargo check --verbose --workspace --exclude plugin-host-gui
        if: matrix.os == 'macos-latest'
  build-rust:
    name: Build release rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: ./scripts/install-ubuntu-dependencies.sh
      if: matrix.os == 'ubuntu-latest'
    - name: Build release
      run: cargo build --release --verbose --workspace --exclude plugin-host-gui
      if: matrix.os == 'macos-latest'
    - name: Non-OSX build release
      run: |
        cargo build --release --verbose --workspace \
            --exclude plugin-host-gui \
            --exclude darwin-webkit \
            --exclude macos-bundle-resources
      if: matrix.os != 'macos-latest'
    - name: Upload plugin-host binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host
        path: ./target/release/plugin-host
    - name: Upload plugin-host-gui2 binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host-gui2
        path: ./target/release/plugin-host-gui2
    - name: Upload tremolo-plugin dylib
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-libtas_v2-dylib
        path: ./target/release/libtas_v2.dylib

