name: Default

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    name: Build rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
            libasound2-dev \
            libssl-dev \
            cmake \
            libfreetype6-dev \
            expat \
            libexpat1-dev \
            libglib2.0-dev \
            libcairo-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libgdk-pixbuf2.0-dev \
            libsoup2.4-dev \
            libclang-11-dev \
            libgdk3.0-cil-dev \
            libappindicator3-dev \
            libgtksourceview-3.0-dev \
            libwebkit2gtk-4.0-dev \
            libx11-xcb-dev \
            libxcb-icccm4-dev \
            libxcb-dri2-0-dev \
            nvidia-utils-465 \
            libgtk-3-dev
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test --verbose --workspace --exclude plugin-host-gui
      if: matrix.os == 'macos-latest'
    - name: Run clippy
      run: cargo clippy --verbose --workspace --exclude plugin-host-gui
      if: matrix.os == 'macos-latest'
    - name: Run check
      run: cargo check --verbose --workspace --exclude plugin-host-gui
      if: matrix.os == 'macos-latest'
    - name: Build
      run: cargo build --release --verbose --workspace --exclude plugin-host-gui
      if: matrix.os == 'macos-latest'
    - name: Non-OSX test
      run: |
        cargo test --no-default-features --verbose --workspace \
            --features story \
            --exclude plugin-host-gui \
            --exclude darwin-webkit \
            --exclude webview-holder \
            --exclude macos-bundle-resources
    - name: Non-OSX build
      run: |
        cargo build --release --verbose --workspace \
            --exclude plugin-host-gui \
            --exclude darwin-webkit \
            --exclude macos-bundle-resources
      if: matrix.os != 'macos-latest'
    - name: Upload plugin-host binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host
        path: ./target/release/plugin-host
    - name: Upload plugin-host-gui2 binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host-gui2
        path: ./target/release/plugin-host-gui2
    - name: Upload tremolo-plugin dylib
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-libtas_v2-dylib
        path: ./target/release/libtas_v2.dylib

