name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    name: Rust - Run unit-tests on rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-test-cache
      - uses: Swatinem/rust-cache@v1
      - name: Install uniffi bindgen
        run: |
          if ! [ -x "$(command -v uniffi-bindgen)" ]; then
            cargo install --force --version 0.15.2 uniffi_bindgen
          fi
      - name: Run tests
        run: cargo test --verbose --workspace --features story --exclude augmented-ui --exclude midir
  lint-rust:
    name: Rust - Lint rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-lint-cache
      - uses: Swatinem/rust-cache@v1
      - name: Install uniffi bindgen
        run: |
          if ! [ -x "$(command -v uniffi-bindgen)" ]; then
            cargo install --force --version 0.15.2 uniffi_bindgen
          fi
      - name: Run clippy
        run: cargo clippy --features story --workspace --exclude skribo --exclude augmented-ui --exclude midir
      - name: Run check
        run: cargo check --verbose --workspace --features story --exclude augmented-ui --exclude midir
  build-rust:
    name: Rust - Build release rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-release-cache
    - uses: Swatinem/rust-cache@v1
    - name: Install uniffi bindgen
      run: cargo install --force --version 0.15.2 uniffi_bindgen
    - name: Build release
      run: cargo build --release --verbose --workspace --exclude augmented-ui --exclude midir
    - name: Run snapshot tests
      run: |
        ./scripts/dev.sh test-snapshots
    - name: Upload plugin-host binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host
        path: ./target/release/plugin-host
    - name: Upload plugin-host-gui2 binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host-gui2
        path: ./target/release/plugin-host-gui2
    - name: Upload tremolo-plugin dylib
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-libtas_v2-dylib
        path: ./target/release/libtas_v2.dylib

