name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rust:
    name: Rust - Run unit-tests on rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-macos2"

      - name: Cache cargo binaries
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-bin

      - name: Install cargo-nextest
        run: |
          ls ~/.cargo/bin/
          if ! [ -x "$(command -v cargo-nextest)" ]; then
            echo "::group::Installing cargo-nextest"
            curl -LsSf https://get.nexte.st/latest/mac | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
            echo "::endgroup::"
          fi
          which cargo-nextest
      - name: Install uniffi bindgen
        run: |
          if ! [ -x "$(command -v uniffi-bindgen)" ]; then
            echo "::group::Installing uniffi_bindgen"
            cargo install --force --version 0.15.2 uniffi_bindgen
            echo "::endgroup::"
          fi
          which uniffi-bindgen
      - name: Run tests
        run: ./scripts/test.sh

  lint-rust:
    name: Rust - Lint rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-macos2"
      - name: Run clippy
        run: ./scripts/clippy.sh

  build-rust:
    name: Rust - Build release rust crates ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true

    - name: Set up sccache
      env:
        SCCACHE_VERSION: 0.4.0
        PLATFORM: x86_64-apple-darwin
      run: |
        SCCACHE_FILE=sccache-dist-v$SCCACHE_VERSION-$PLATFORM
        SCCACHE_URL=https://github.com/mozilla/sccache/releases/download/v$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz
        curl -L $SCCACHE_URL | tar xz
        mv "$(pwd)/$SCCACHE_FILE/sccache-dist" "$(pwd)/$SCCACHE_FILE/sccache"
        echo "$(pwd)/$SCCACHE_FILE/sccache" >> $GITHUB_PATH
        ls "$(pwd)/$SCCACHE_FILE"

    - name: Cache sccache output
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/sccache
        key: ${{ runner.os }}-sccache-releasebuild-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
            ${{ runner.os }}-sccache-releasebuild

    - name: Print sccache stats
      run: |
        sccache -s

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "rust-cache-macos2"
    - name: Cache cargo binaries
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
        key: ${{ runner.os }}-cargo-bin

    - name: Install uniffi bindgen
      env:
        RUSTC_WRAPPER: sccache
      run: |
        if ! [ -x "$(command -v uniffi-bindgen)" ]; then
          echo "::group::Installing uniffi_bindgen"
          cargo install --force --version 0.15.2 uniffi_bindgen
          echo "::endgroup::"
        fi
        which uniffi-bindgen

    - name: Build release
      env:
        RUSTC_WRAPPER: sccache
      run: cargo build --release --verbose --workspace --exclude augmented-ui --exclude midir

    - name: Print sccache stats
      run: |
        sccache -s

    - name: Upload plugin-host binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host
        path: ./target/release/plugin-host
    - name: Upload plugin-host-gui2 binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-plugin-host-gui2
        path: ./target/release/plugin-host-gui2
    - name: Upload tremolo-plugin dylib
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-libtas_v2-dylib
        path: ./target/release/libtas_v2.dylib
    - name: Validate license information
      run: |
        if ! [ -x "$(command -v cargo-about)" ]; then
          cargo install cargo-about
        fi
        cargo about generate about.hbs



  run-snapshot-tests:
    name: Run snapshot tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "rust-cache-macos2"
    - name: Run snapshot tests
      run: |
        ./scripts/dev.sh test-snapshots
    - name: Upload snapshot test results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-snapshot-tests
        path: ./test
      if: ${{ failure() }}

  build-sequencer:
    name: Build Continuous looper
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-macos2"
      - name: Cache cargo binaries
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-bin
      - name: Install cargo-lipo
        run: |
          if ! [ -x "$(command -v cargo-lipo)" ]; then
            cargo install cargo-lipo
          fi
      - name: Install ARM/x86 toolchains
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-ios-sim
          rustup target add aarch64-apple-ios
      - name: Build looper universal libraries
        run: |
          cd ./crates/apps/looper/looper-processor
          make
      - uses: actions/cache@v2
        name: "Cache: Swift Package Manager"
        with:
          path: ~/Library/Developer/Xcode/DerivedData/Sequencer-*/SourcePackages/
          key: ${{ runner.os }}-spm
          restore-keys: |
            ${{ runner.os }}-spm
      - name: Run Sequencer.app tests
        run: |
          cd ./crates/apps/looper/Sequencer
          brew install xcbeautify
          make test
