name: Documentation

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docs:
    name: Build documentation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.2
        with:
          version: "v0.4.0"
      - uses: subosito/flutter-action@v1
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache-macos-docs"
          cache-all-crates: true
          cache-on-failure: true
      - name: Build documentation
        run: cargo doc --no-deps
        env:
          SCCACHE_GHA_ENABLED: true
          RUSTC_WRAPPER: sccache
