name: JavaScript

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: restore lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install lerna
      run: npm install
    - name: Bootstrap packages
      run: ./node_modules/.bin/lerna bootstrap
    - name: Run tests
      run: npm run test
    - name: Run builds
      run: npm run build
    - name: Upload tremolo-plugin-frontend build
      uses: actions/upload-artifact@v2
      with:
        name: tremolo-plugin-frontend
        path: ./packages/tremolo-plugin-frontend/build
    - name: Upload plugin-host-gui build
      uses: actions/upload-artifact@v2
      with:
        name: plugin-host-gui
        path: ./crates/plugin-host-gui/build

