name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose --workspace --exclude plugin-host-gui
    - name: Run tests
      run: cargo test --verbose --workspace --exclude plugin-host-gui
    - name: Run clippy
      run: cargo clippy --verbose --workspace --exclude plugin-host-gui
    - name: Run check
      run: cargo check --verbose --workspace --exclude plugin-host-gui
