name: Rust CI

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  build-rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-20.04]
      fail-fast: false
    name: Build rust crates on ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/common
        with:
          cache_key: ${{ inputs.os }}_build
      - name: Run build
        run: cargo build
      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: build_target
          path: target
          retention-days: 0

  test-rust:
    needs:
      - build-rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-20.04]
      fail-fast: false
    name: Test rust crates on ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/common
        with:
          cache_key: ${{ inputs.os }}_test
      - name: Download build target
        uses: actions/download-artifact@v4
        with:
          name: build_target
      - name: Run tests
        run: ./scripts/test.sh

  lint-rust:
    needs:
      - build-rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-20.04]
      fail-fast: false
    name: Test rust crates on ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/actions/common
        with:
          cache_key: ${{ inputs.os }}_lint
      - name: Download build target
        uses: actions/download-artifact@v4
        with:
          name: build_target
      - name: Run clippy
        run: ./scripts/clippy.sh