name: Web-based builds

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-javascript:
    name: Build legacy JavaScript apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install lerna
        run: npm install
      - name: Bootstrap packages
        run: ./node_modules/.bin/lerna bootstrap --hoist
      - name: Run tests
        run: npm run test
      - name: Run builds
        run: npm run build
      - name: Upload tremolo-plugin-frontend build
        uses: actions/upload-artifact@v2
        with:
          name: tremolo-plugin-frontend
          path: ./packages/tremolo-plugin-frontend/build
